### PR TITLE
Update AsyncWebSocket.cpp

### PR DESCRIPTION
**Pull request by CRSLEE**

### CODE REVIEW

**Comment by thorrak** [comment]
+1 on this

**Comment by bjun626** [comment]
+1

**Comment by munzili** [comment]
+1

**Comment by rob040** [comment]
@asjdf: This change (#10) causes compilation error in platformIO esp32:
```
Compiling .pio\build\esp32dev_dbg\liba26\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o
.pio/libdeps/esp32dev_dbg/ESPAsyncWebServer-esphome/src/AsyncWebSocket.cpp: In function 'size_t webSocketSendFrame(AsyncClient*, bool, uint8_t, bool, uint8_t*, size_t)':
.pio/libdeps/esp32dev_dbg/ESPAsyncWebServer-esphome/src/AsyncWebSocket.cpp:105:7: warning: init-statement in selection statements only available with -std=c++17 or -std=gnu++17
   if (!client->send();) return 0;
       ^
.pio/libdeps/esp32dev_dbg/ESPAsyncWebServer-esphome/src/AsyncWebSocket.cpp:105:23: error: expected primary-expression before ')' token
   if (!client->send();) return 0;
                       ^
*
** [.pio\build\esp32dev_dbg\liba26\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o] Error 1
```
Removing the ';' solves the error.

**Comment by asjdf** [comment]
> 

I noticed this issue and previous PR #17 could fix this issue too, thanks for your notice and I am trying to contact the maintainer of this lib.❤️

**Comment by jesserockz** [comment]
Apologies this was not noticed and merged earlier. 
Closing as https://github.com/esphome/ESPAsyncWebServer/pull/17 has been merged.

**Pull request closed without merging**
