### PR TITLE
ArduinoJson 7 Compatibility

### PR DESCRIPTION
**Pull request by mathieucarbou**
[ArduinoJson 7](https://github.com/bblanchon/ArduinoJson) now being released, a lot of projets will want to switch to it, but the move should start first with libraries.

[ESPAsyncWebServer](https://github.com/esphome/ESPAsyncWebServer) being widely used and also maintained by ESPHome, I strongly suggest to consider this PR as an addition in order to help people migrate to ArduinoJson 7, and at the same time push people towards using this maintained repository instead of the [original and unmaintained one](https://github.com/me-no-dev/ESPAsyncWebServer)

### CODE REVIEW

**Comment by mathieucarbou** [comment]
CC @ bblanchon

**Comment by bblanchon** [comment]
ArduinoJson 7 is code-compatible with ArduinoJson 6, so there is no hurry.
However, you'll see some compilation warnings if you call deprecated functions.

**Comment by mathieucarbou** [comment]
> ArduinoJson 7 is code-compatible with ArduinoJson 6, so there is no hurry. However, you'll see some compilation warnings if you call deprecated functions.

True but behaviours are not the same regarding stack and heap usage and compiling with `-Wall -Wextra -Werror` is failing here ;-)

**Comment by zekageri** [comment]
I would consider moving from async tcp to Psychic lib.

**Comment by StefanoTesla** [comment]
> ArduinoJson 7 is code-compatible with ArduinoJson 6, so there is no hurry.

For the moment....

**Comment by mathieucarbou** [comment]
> I would consider moving from async tcp to Psychic lib.
> 
> https://github.com/hoeken/PsychicHttp

Sincerely, I would (I saw who contributes to this project and know who they are).

But when you use a lot of libraries depending on AsyncTCP and ESPASyncWebServer, like many other people, I really think that this should be instead up to PsychicHttp devs to provide a good migration path (api compatibility) to facilitate the switch. Switching is only possible on project not using a lot of dependencies, which limits a lot the adoption of PsychicHttp to only a few use cases sadly. Besides, `ESPAsyncWebServer` works great once all the concurrency issues fixed. I agree, performance is not comparable. But ESP32 devices are mostly small projects / IoT projects so the ecosystem compatibility might come first in need, way before having something performant.

FYI I am now maintaining a fork which is up to date with the improvements from ESPHome team + yubox + some other changes: https://github.com/mathieucarbou/ESPAsyncWebServer

**Comment by pryankster** [comment]
This PR is marked as closed, but doesn't seem to have been merged ... I know that AJ7 is backwards compatible with AJ6, but the deprecation warnings bother me :-) ... any chance of these changes being merged so I don't have to fork?

**Comment by mathieucarbou** [comment]
> This PR is marked as closed, but doesn't seem to have been merged ... I know that AJ7 is backwards compatible with AJ6, but the deprecation warnings bother me :-) ... any chance of these changes being merged so I don't have to fork?

Have a look at https://github.com/mathieucarbou/ESPAsyncWebServer : this a community maintained fork and it has a lot of improvements in terms of memory, perf and new features such as middleware.

**Comment by StefanoTesla** [comment]
> This PR is marked as closed, but doesn't seem to have been merged ... I know that AJ7 is backwards compatible with AJ6, but the deprecation warnings bother me :-) ... any chance of these changes being merged so I don't have to fork?

Consider the answer of @mathieucarbou, my file was modificated just to make it work, I have no idea if I made mistakes😂

**Comment by pryankster** [comment]
Thanks!  Switched to @mathieucarbou version ... got AJ7 support and CORS for free, which I was looking at adding just this morning.

**Pull request closed without merging**
